#!/bin/sh -Cue

# auto-parallelize; note: uses from $PATH and not from repo
if jobsv_sh="$(which jobsv.sh 2>/dev/null)"; then
    . "$jobsv_sh"
    jobsv_or_exec "$0" "$@"
else
    jobsv_bg() { "$@" </dev/null; }
    fi

proj="$(dirname "$0")/.."
[ -d "$proj/.redo" ] || mkdir "$proj/.redo"

if [ $# != 0 ]; then
    exec redo-ifchange "$@"
    fi

findr() { # find regular (non-hidden) names
    src="$1"
    shift
    find "$src" ! -name . -name '.*' -prune -o '(' "$@" ')' -print
    }

cd "$proj"
findr . -type f -name '*.link' \
| while read -r x; do
    [ -e "$x" ] || continue
    x="${x%.link}"
    case "$x" in
        ./src/*)
            printf %s\\0 "cmd/${x#./src/}"
            ;;
        *)
            printf %s\\0 "$x"
            ;;
        esac
    done \
| xargs -0 redo-ifchange
